repos:
  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy
        language: system
        pass_filenames: true
        files: \.(c|h)$
        args:
          - "--"
          - "-std=c99"
