version: '3'
services:
  can_sender:
    # image: emanueladler/can-sender:latest
    build: .
    container_name: sender
    network_mode: "host"
    command: ["./bin/sh", "-c", "mkfifo /tmp/can_pipe && ./bin/sender"]

  ecu_powertrain:
    # image: emanueladler/can-receiver:latest
    build: .
    container_name: receiver
    network_mode: "host"
    command: ["./bin/receiver"]

  ecu_instrument_cluster:
    # image: emanueladler/can-receiver:latest
    build: .
    container_name: receiver
    network_mode: "host"
    command: ["./bin/receiver"]

  ecu_bcm:
    # image: emanueladler/can-receiver:latest
    build: .
    container_name: receiver
    network_mode: "host"
    command: ["./bin/receiver"]

  ecu_climatization:
    # image: emanueladler/can-receiver:latest
    build: .
    container_name: receiver
    network_mode: "host"
    command: ["./bin/receiver"]
