version: '3'
services:
  ecu_dashboard:
    tty: true
    image: paulormn/dashboard:latest
    build: .
    container_name: dashboard
    network_mode: "host"
    command: ["./bin/dashboard"]
    volumes:
      - ss_logs_volume:/app/logs
    environment:
      - TERM=xterm-256color
      - COLUMNS=130
      - LINES=20
    cap_add:
      - SYS_PTRACE  # Needed for terminal operations

  ecu_powertrain:
    image: paulormn/powertrain:latest
    build: .
    container_name: powertrain
    network_mode: "host"
    command: ["./bin/powertrain"]
    volumes:
      - ss_logs_volume:/app/logs

  ecu_instrument_cluster:
    image: paulormn/instrument_cluster:latest
    build: .
    container_name: instrument_cluster
    network_mode: "host"
    command: ["./bin/instrument_cluster"]
    volumes:
      - ss_logs_volume:/app/logs

  ecu_bcm:
    image: paulormn/bcm:latest
    build: .
    container_name: bcm
    network_mode: "host"
    command: ["./bin/bcm"]
    volumes:
      - ss_logs_volume:/app/logs

volumes:
  ss_logs_volume:
