version: '3'
services:
  can_sender:
    build: .
    container_name: can_sender
    network_mode: "host"
    command: ["./bin/sender"]
    volumes:
      - ss_logs_volume:/app/logs

  ecu_powertrain:
    build: .
    container_name: powertrain
    network_mode: "host"
    command: ["./bin/receiver"]
    volumes:
      - ss_logs_volume:/app/logs

  ecu_instrument_cluster:
    build: .
    container_name: instrument_cluster
    network_mode: "host"
    command: ["./bin/receiver"]
    volumes:
      - ss_logs_volume:/app/logs

  ecu_bcm:
    build: .
    container_name: bcm
    network_mode: "host"
    command: ["./bin/receiver"]
    volumes:
      - ss_logs_volume:/app/logs

  ecu_climatization:
    build: .
    container_name: climatization
    network_mode: "host"
    command: ["./bin/receiver"]
    volumes:
      - ss_logs_volume:/app/logs

volumes:
  ss_logs_volume:
