name: Run Unit Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC 14.2.0 and build dependencies
        run: |
          sudo apt update
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install -y gcc-14 g++-14 make build-essential can-utils \
            clang libssl-dev libcunit1 libcunit1-doc libcunit1-dev \
            linux-modules-extra-$(uname -r)
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
          gcc --version

      - name: Setup virtual CAN interface
        run: sudo ./setup_vcan.sh

      - name: Build and run unit tests
        run: |
          cd tests/
          make clean
          make all
          make test
